"""
Script to generate an academic, publication-quality PDF report from project_report.md
using Python markdown and Microsoft Edge headless PDF engine.
"""

import sys
import subprocess
from pathlib import Path
import markdown

REPORT_DIR = Path(__file__).resolve().parent.parent / "report"
OUTPUTS_DIR = Path(__file__).resolve().parent.parent / "outputs"
MD_FILE = REPORT_DIR / "project_report.md"
HTML_FILE = REPORT_DIR / "project_report.html"
PDF_FILE = REPORT_DIR / "project_report.pdf"
EDGE_EXE = Path(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")


def convert_md_to_html() -> None:
    """Read markdown, inject CSS styling, and write styled HTML."""
    with open(MD_FILE, "r", encoding="utf-8") as f:
        md_text = f.read()

    # Convert markdown to HTML with tables, code fences, etc.
    html_body = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "toc", "nl2br", "sane_lists"]
    )

    # Convert ```mermaid code blocks to <div class="mermaid">
    html_body = html_body.replace('<pre><code class="language-mermaid">', '<div class="mermaid">')
    html_body = html_body.replace('</code></pre>', '</div>')

    # Convert absolute/relative image paths if any exist
    enhanced_img_uri = (OUTPUTS_DIR / "enhanced.png").as_uri()
    matches_img_uri = (OUTPUTS_DIR / "feature_matches.png").as_uri()
    epipolar_img_uri = (OUTPUTS_DIR / "epipolar_composite.png").as_uri()
    stereo_img_uri = (OUTPUTS_DIR / "disparity_depth_analysis.png").as_uri()
    edge_img_uri = (OUTPUTS_DIR / "edge_segmentation_summary.png").as_uri()

    # Embed visual gallery section into HTML
    gallery_html = f"""
    <div class="page-break"></div>
    <h2>Appendix: Empirical Visual Artifacts Gallery</h2>
    <p>The following visual outputs were generated by the system during end-to-end execution of the full analysis pipeline:</p>
    
    <div class="figure-container">
        <h3>Figure A1: Image Enhancement & Intensity Histograms</h3>
        <img src="{enhanced_img_uri}" alt="Enhancement Comparison" style="max-width:100%; border-radius:4px; border:1px solid #ddd;" />
        <p class="caption">Comparison of original RGB, grayscale luminance, Gaussian blur, CLAHE contrast enhancement, unsharp mask sharpening, and intensity distributions.</p>
    </div>

    <div class="figure-container">
        <h3>Figure A2: Spatial Derivatives & Region Segmentation</h3>
        <img src="{edge_img_uri}" alt="Edge & Segmentation" style="max-width:100%; border-radius:4px; border:1px solid #ddd;" />
        <p class="caption">Sobel X/Y derivatives, gradient magnitude field, Canny 1-pixel thin edges, Otsu binary thresholding, and labeled connected component regions.</p>
    </div>

    <div class="figure-container">
        <h3>Figure A3: SIFT Feature Correspondences (Lowe's Ratio Test)</h3>
        <img src="{matches_img_uri}" alt="Feature Matches" style="max-width:100%; border-radius:4px; border:1px solid #ddd;" />
        <p class="caption">Pairwise SIFT keypoint matches passing Lowe's ratio test (&tau; = 0.75), eliminating ambiguous and repetitive pattern matches.</p>
    </div>

    <div class="figure-container">
        <h3>Figure A4: Epipolar Geometry & Conjugate Epipolar Lines</h3>
        <img src="{epipolar_img_uri}" alt="Epipolar Lines" style="max-width:100%; border-radius:4px; border:1px solid #ddd;" />
        <p class="caption">Side-by-side visualization of conjugate epipolar lines satisfying the fundamental matrix constraint x2^T * F * x1 = 0.</p>
    </div>

    <div class="figure-container">
        <h3>Figure A5: Stereo Disparity & Metric Depth Recovery (Z = fB / d)</h3>
        <img src="{stereo_img_uri}" alt="Disparity & Depth" style="max-width:100%; border-radius:4px; border:1px solid #ddd;" />
        <p class="caption">Left view, dense false-color disparity map (StereoSGBM), metric depth map, and pixel depth distribution histogram.</p>
    </div>
    """

    styled_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CV-Scope Academic Project Report</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
        mermaid.initialize({{
            startOnLoad: true,
            theme: 'default',
            securityLevel: 'loose'
        }});
    </script>
    <style>
        @page {{
            size: A4;
            margin: 18mm 16mm 18mm 16mm;
            @bottom-right {{
                content: counter(page);
            }}
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #24292f;
            line-height: 1.6;
            font-size: 13.5px;
            background-color: #ffffff;
            margin: 0;
            padding: 10px;
        }}
        h1 {{
            font-size: 24px;
            border-bottom: 2px solid #0969da;
            padding-bottom: 8px;
            color: #1f2328;
            margin-top: 20px;
        }}
        h2 {{
            font-size: 18px;
            border-bottom: 1px solid #d0d7de;
            padding-bottom: 6px;
            color: #1f2328;
            margin-top: 24px;
            page-break-after: avoid;
        }}
        h3 {{
            font-size: 15px;
            color: #24292f;
            margin-top: 16px;
            page-break-after: avoid;
        }}
        p, li {{
            text-align: justify;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 16px 0;
            font-size: 12.5px;
            page-break-inside: avoid;
        }}
        th, td {{
            border: 1px solid #d0d7de;
            padding: 7px 10px;
            text-align: left;
        }}
        th {{
            background-color: #f6f8fa;
            font-weight: 600;
        }}
        tr:nth-child(even) {{
            background-color: #fcfcfc;
        }}
        pre, code {{
            font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
            font-size: 12px;
        }}
        pre {{
            background-color: #f6f8fa;
            border: 1px solid #d0d7de;
            border-radius: 6px;
            padding: 12px;
            overflow-x: auto;
            page-break-inside: avoid;
        }}
        code {{
            background-color: rgba(175, 184, 193, 0.2);
            padding: 2px 4px;
            border-radius: 4px;
        }}
        pre code {{
            background-color: transparent;
            padding: 0;
        }}
        blockquote {{
            border-left: 4px solid #0969da;
            padding: 0 15px;
            color: #57606a;
            margin: 12px 0;
            background-color: #f6f8fa;
            border-radius: 0 4px 4px 0;
        }}
        .mermaid {{
            text-align: center;
            margin: 18px 0;
            page-break-inside: avoid;
        }}
        .figure-container {{
            margin: 22px 0;
            text-align: center;
            page-break-inside: avoid;
        }}
        .caption {{
            font-size: 11.5px;
            color: #57606a;
            font-style: italic;
            margin-top: 6px;
        }}
        .page-break {{
            page-break-before: always;
        }}
    </style>
</head>
<body>
{html_body}
{gallery_html}
</body>
</html>
"""

    with open(HTML_FILE, "w", encoding="utf-8") as f:
        f.write(styled_html)
    print(f"Generated intermediate styled HTML: {HTML_FILE}")


def convert_html_to_pdf() -> None:
    """Use Microsoft Edge headless to print styled HTML to PDF."""
    if not EDGE_EXE.exists():
        raise FileNotFoundError(f"Microsoft Edge executable not found at {EDGE_EXE}")

    cmd = [
        str(EDGE_EXE),
        "--headless",
        "--disable-gpu",
        "--no-pdf-header-footer",
        "--run-all-compositor-stages-before-draw",
        "--virtual-time-budget=4000",
        f"--print-to-pdf={PDF_FILE.resolve()}",
        str(HTML_FILE.resolve())
    ]

    print("Executing Microsoft Edge headless PDF rendering...")
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        print(f"Edge stderr: {res.stderr}", file=sys.stderr)
        raise RuntimeError(f"Edge failed with return code {res.returncode}")

    if PDF_FILE.exists() and PDF_FILE.stat().st_size > 0:
        print(f"SUCCESS: Generated PDF Report ({PDF_FILE.stat().st_size / 1024:.1f} KB): {PDF_FILE}")
    else:
        raise RuntimeError("PDF file was not created or is empty.")


if __name__ == "__main__":
    convert_md_to_html()
    convert_html_to_pdf()
